/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Igra;
import javax.swing.JOptionPane;
import konstante.Operacije;
import kontroler.Komunikacija;
import modeli.ModelTabeleKlijent;
import niti.CetvrtaNit;
import niti.DrugaNit;
import niti.PrvaNit;
import niti.TrecaNit;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author frado
 */
public class KlijentskaForma extends javax.swing.JFrame {
    private PrvaNit pn;
    private DrugaNit dn;
    private TrecaNit tn;
    private CetvrtaNit cn;
    public int brojPokusaja = 0;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Klijentska forma");
        tbl_igra.setModel(new ModelTabeleKlijent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_start1 = new javax.swing.JButton();
        btn_start2 = new javax.swing.JButton();
        btn_start3 = new javax.swing.JButton();
        btn_start4 = new javax.swing.JButton();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        btn_stop1 = new javax.swing.JButton();
        btn_stop2 = new javax.swing.JButton();
        btn_stop3 = new javax.swing.JButton();
        btn_stop4 = new javax.swing.JButton();
        btn_posalji = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_brojPogodjenihNaMestu = new javax.swing.JLabel();
        lbl_brojPogodjenihNisuNaMestu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_igra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_start1.setText("START");
        btn_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start1ActionPerformed(evt);
            }
        });

        btn_start2.setText("START");
        btn_start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start2ActionPerformed(evt);
            }
        });

        btn_start3.setText("START");
        btn_start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start3ActionPerformed(evt);
            }
        });

        btn_start4.setText("START");
        btn_start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start4ActionPerformed(evt);
            }
        });

        lbl_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_1.setText("0");

        lbl_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_2.setText("0");

        lbl_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_3.setText("0");

        lbl_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_4.setText("0");

        btn_stop1.setText("STOP");
        btn_stop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop1ActionPerformed(evt);
            }
        });

        btn_stop2.setText("STOP");
        btn_stop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop2ActionPerformed(evt);
            }
        });

        btn_stop3.setText("STOP");
        btn_stop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop3ActionPerformed(evt);
            }
        });

        btn_stop4.setText("STOP");
        btn_stop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop4ActionPerformed(evt);
            }
        });

        btn_posalji.setText("POSALJI");
        btn_posalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posaljiActionPerformed(evt);
            }
        });

        jLabel1.setText("Broj pogodjenih na mestu:");

        jLabel2.setText("Broj pogodjenih nisu na mestu:");

        tbl_igra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_igra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(lbl_brojPogodjenihNaMestu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_1)
                        .addGap(118, 118, 118)
                        .addComponent(lbl_2)
                        .addGap(108, 108, 108)
                        .addComponent(lbl_3)
                        .addGap(108, 108, 108)
                        .addComponent(lbl_4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_start1)
                                    .addComponent(btn_stop1))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_start2)
                                    .addComponent(btn_stop2)))
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_brojPogodjenihNisuNaMestu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_start3)
                                    .addComponent(btn_stop3))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_stop4)
                                    .addComponent(btn_start4)
                                    .addComponent(btn_posalji))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_start1)
                    .addComponent(btn_start2)
                    .addComponent(btn_start3)
                    .addComponent(btn_start4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_stop1)
                    .addComponent(btn_stop2)
                    .addComponent(btn_stop3)
                    .addComponent(btn_stop4))
                .addGap(29, 29, 29)
                .addComponent(btn_posalji)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_brojPogodjenihNaMestu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_brojPogodjenihNisuNaMestu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start1ActionPerformed
        pn = new PrvaNit(lbl_1, true);
        pn.start();
    }//GEN-LAST:event_btn_start1ActionPerformed

    private void btn_stop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop1ActionPerformed
        pn.radi = false;
    }//GEN-LAST:event_btn_stop1ActionPerformed

    private void btn_start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start2ActionPerformed
        dn = new DrugaNit(lbl_2, true);
        dn.start();
    }//GEN-LAST:event_btn_start2ActionPerformed

    private void btn_stop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop2ActionPerformed
        dn.radi = false;
    }//GEN-LAST:event_btn_stop2ActionPerformed

    private void btn_start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start3ActionPerformed
        tn = new TrecaNit(lbl_3, true);
        tn.start();
    }//GEN-LAST:event_btn_start3ActionPerformed

    private void btn_stop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop3ActionPerformed
        tn.radi = false;
    }//GEN-LAST:event_btn_stop3ActionPerformed

    private void btn_start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start4ActionPerformed
        cn = new CetvrtaNit(lbl_4, true);
        cn.start();
    }//GEN-LAST:event_btn_start4ActionPerformed

    private void btn_stop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop4ActionPerformed
        cn.radi = false;
    }//GEN-LAST:event_btn_stop4ActionPerformed

    private void btn_posaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posaljiActionPerformed
        
        int prviBroj = Integer.parseInt(lbl_1.getText());
        int drugiBroj = Integer.parseInt(lbl_2.getText());
        int treciBroj = Integer.parseInt(lbl_3.getText());
        int cetvrtiBroj = Integer.parseInt(lbl_4.getText());
        
        int[] niz = new int[5];
        niz[0] = prviBroj;
        niz[1] = drugiBroj;
        niz[2] = treciBroj;
        niz[3] = cetvrtiBroj;
        niz[4] = ++brojPokusaja;
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacije(Operacije.POSALJI);
        kz.setParametar(niz);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        Igra igra = (Igra) so.getOdgovor();
        
        if (igra == null) {
            JOptionPane.showMessageDialog(this, "Greska prilikom slanja kombinacije!");
        }
        else{
            ModelTabeleKlijent mt = (ModelTabeleKlijent) tbl_igra.getModel();
            mt.dodajIgru(igra);
            
            lbl_brojPogodjenihNaMestu.setText(String.valueOf(igra.getPogodjeniNaMestu()));
            lbl_brojPogodjenihNisuNaMestu.setText(String.valueOf(igra.getPogodjeniNisuNaMestu()));
            
            if (igra.getPogodjeniNaMestu() == 4) {
                JOptionPane.showMessageDialog(this, "Pobedili ste");
                System.exit(0);
            }
            
            if (brojPokusaja == 6) {
                JOptionPane.showMessageDialog(this, "Zao mi je dostigli ste max pokusaja");
                System.exit(0);
            }
            else{
                JOptionPane.showMessageDialog(this, "Broj preostalih pokusaja je " + (6 - brojPokusaja));
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_btn_posaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                KlijentskiZahtev kz = new KlijentskiZahtev();
                kz.setOperacije(Operacije.POKRENI);
                Komunikacija.getInstance().posaljiZahtev(kz);
                ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                boolean uspesno = (boolean) so.getOdgovor();
                
                if (uspesno) {
                    new KlijentskaForma().setVisible(true);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_posalji;
    private javax.swing.JButton btn_start1;
    private javax.swing.JButton btn_start2;
    private javax.swing.JButton btn_start3;
    private javax.swing.JButton btn_start4;
    private javax.swing.JButton btn_stop1;
    private javax.swing.JButton btn_stop2;
    private javax.swing.JButton btn_stop3;
    private javax.swing.JButton btn_stop4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_brojPogodjenihNaMestu;
    private javax.swing.JLabel lbl_brojPogodjenihNisuNaMestu;
    private javax.swing.JTable tbl_igra;
    // End of variables declaration//GEN-END:variables
}
